CREATE TABLE perfumes(

    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)     NOT NULL,
    brand           VARCHAR(50)     NOT NULL,
    description     VARCHAR(250)    NOT NULL,
    family          VARCHAR(50)     NOT NULL,
    concentration   VARCHAR(50)     NOT NULL,
    gender          VARCHAR(50)     NOT NULL,
    volume_ml       INTEGER         NOT NULL,
    price           NUMERIC(6, 2)   NOT NULL,
    stock           INTEGER         NOT NULL,
    image_url       VARCHAR(255),
    CONSTRAINT chk_stock_non_negative CHECK (stock >= 0)


);