-- V7: catálogo reutilizable de notas olfativas + pirámide (top/heart/base) por perfume.

CREATE TABLE notes (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50) NOT NULL,
    CONSTRAINT uq_notes_name UNIQUE (name)
);

CREATE TABLE perfume_notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfume_id  BIGINT NOT NULL REFERENCES perfumes(id),
    note_id     BIGINT NOT NULL REFERENCES notes(id),
    level       VARCHAR(10) NOT NULL,
    CONSTRAINT uq_perfume_notes_perfume_note UNIQUE (perfume_id, note_id)
);

-- 1. Catálogo de notas reutilizables (~40)
INSERT INTO notes (name) VALUES
    ('Bergamota'), ('Limón'), ('Pomelo'), ('Naranja'), ('Piña'),
    ('Lavanda'), ('Cardamomo'), ('Azafrán'), ('Pimienta rosa'), ('Abedul'),
    ('Rosa'), ('Jazmín'), ('Iris'), ('Violeta'), ('Higo verde'),
    ('Salvia'), ('Canela'), ('Trufa'), ('Coñac'), ('Lácteas'),
    ('Oud'), ('Sándalo'), ('Cedro'), ('Vetiver'), ('Pachulí'),
    ('Ámbar'), ('Vainilla'), ('Almizcle'), ('Benjuí'), ('Haba tonka'),
    ('Cuero'), ('Tabaco'), ('Frutos secos'), ('Almizcle blanco'), ('Miel'),
    ('Incienso'), ('Musgo de roble'), ('Geranio'), ('Pimienta negra'), ('Coco'), ('Ládano');

-- 2. Perfumes originales (V2)

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Cardamomo', 'TOP'), ('Bergamota', 'TOP'),
    ('Oud', 'HEART'), ('Rosa', 'HEART'),
    ('Sándalo', 'BASE'), ('Ámbar', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Oud Wood' AND p.brand = 'Tom Ford';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Cardamomo', 'TOP'), ('Pimienta rosa', 'TOP'),
    ('Lavanda', 'HEART'), ('Salvia', 'HEART'),
    ('Cedro', 'BASE'), ('Vetiver', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'La Nuit de l''Homme' AND p.brand = 'Yves Saint Laurent';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Trufa', 'TOP'), ('Bergamota', 'TOP'),
    ('Jazmín', 'HEART'), ('Iris', 'HEART'),
    ('Pachulí', 'BASE'), ('Incienso', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Black Orchid' AND p.brand = 'Tom Ford';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Piña', 'TOP'), ('Abedul', 'TOP'),
    ('Rosa', 'HEART'), ('Jazmín', 'HEART'),
    ('Almizcle', 'BASE'), ('Musgo de roble', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Aventus' AND p.brand = 'Creed';

-- 3. Perfumes añadidos en V6

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Cardamomo', 'TOP'), ('Canela', 'TOP'),
    ('Ámbar', 'HEART'), ('Miel', 'HEART'),
    ('Vainilla', 'BASE'), ('Haba tonka', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Khamrah' AND p.brand = 'Lattafa';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Higo verde', 'TOP'), ('Bergamota', 'TOP'),
    ('Lácteas', 'HEART'), ('Jazmín', 'HEART'),
    ('Cedro', 'BASE'), ('Almizcle blanco', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Fig Blossom' AND p.brand = 'Zara';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Naranja', 'TOP'), ('Ládano', 'TOP'),
    ('Benjuí', 'HEART'), ('Lavanda', 'HEART'),
    ('Vainilla', 'BASE'), ('Ámbar', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Grand Soir' AND p.brand = 'Maison Francis Kurkdjian';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Pimienta negra', 'TOP'), ('Cardamomo', 'TOP'),
    ('Cuero', 'HEART'), ('Tabaco', 'HEART'),
    ('Vainilla', 'BASE'), ('Frutos secos', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Tobacco Vanille' AND p.brand = 'Tom Ford';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Azafrán', 'TOP'), ('Rosa', 'TOP'),
    ('Oud', 'HEART'), ('Cuero', 'HEART'),
    ('Ámbar', 'BASE'), ('Almizcle', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Bade''e Al Oud' AND p.brand = 'Lattafa';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Lavanda', 'TOP'), ('Bergamota', 'TOP'),
    ('Salvia', 'HEART'), ('Geranio', 'HEART'),
    ('Cedro', 'BASE'), ('Ámbar', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Y Le Parfum' AND p.brand = 'Yves Saint Laurent';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Coñac', 'TOP'), ('Canela', 'TOP'),
    ('Miel', 'HEART'), ('Haba tonka', 'HEART'),
    ('Vainilla', 'BASE'), ('Ámbar', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Angels'' Share' AND p.brand = 'By Kilian';

INSERT INTO perfume_notes (perfume_id, note_id, level)
SELECT p.id, n.id, v.level
FROM perfumes p
JOIN (VALUES
    ('Limón', 'TOP'), ('Pomelo', 'TOP'),
    ('Naranja', 'HEART'), ('Geranio', 'HEART'),
    ('Ámbar', 'BASE'), ('Almizcle blanco', 'BASE')
) AS v(note, level) ON true
JOIN notes n ON n.name = v.note
WHERE p.name = 'Erba Pura' AND p.brand = 'Xerjoff';
